/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.ciandt.deck;

import java.util.List;

import com.ciandt.deck.playingcard.PlayingCard;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RestController;

@SpringBootApplication
@RestController
public class App {
    @GetMapping("/")
    public List<PlayingCard> getGreeting() {
        return CardDeck.getDeck();
    }

    public static void main(String[] args) {
        SpringApplication.run(App.class, args);
    }
}
